### ISSUE TITLE
stxl16200

### ISSUE THREAD

**Issue by stxlissues** [cedric-r/ASCOM.HomeMade.SBIGCamera#11]
The imaging camera driver loads and works in Prism 10 Advanced, but only produces a 640x480 image instead of the 4500x3600 image.  Actually, both the imaging and external drivers load and all 3 of the drivers produce a 640x480 image.  Is that built in to the driver?

**Comment by cedric-r** [comment]
Hi there,
No that's strange. The resolution is taken from what the camera says it can do and the readmode. Could you activate logging (in the driver options) and sent the logs to me please? (They should be in your user's appdata folder).
Thanks.

**Comment by stxlissues** [comment]
Thanks

**Comment by stxlissues** [comment]
Cedric,

I do not seem to get this problem when I used the imaging driver in SkyX Pro.  The guiding camera seems to work also when I use an external camera.  Is there a configuration that uses both the self-guided filter wheel guide chip and the AO-X unit?

-Al Ryan (stxlissues)

**Comment by stxlissues** [comment]
![Capture](https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/assets/152677558/6ce110cd-d9fd-4ada-b760-059fdfce3792)
[SBIGImagingCamera_2023122333882.log](https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/files/13533851/SBIGImagingCamera_2023122333882.log)

**Comment by cedric-r** [comment]
Thanks.

The driver returns the right sensor size for all the modes. The default bin 1x1 being:
2/12/2023 3:3:38.656: Connected Set:     Binning mode: RM_1X1
2/12/2023 3:3:38.656: Connected Set:     Width: 4500
2/12/2023 3:3:38.657: Connected Set:     Height: 3600
2/12/2023 3:3:38.657: Connected Set:     Gain: 0.87 e-/ADU
2/12/2023 3:3:38.658: Connected Set:     Pixel width: 600
2/12/2023 3:3:38.658: Connected Set:     Pixel height: 600

The reason why the images are so small is that Prism sets the size before taking the image to 648x488:
2/12/2023 3:3:47.839: NumX set: 648
2/12/2023 3:3:47.841: NumY set: 488

I don't know why it chooses these dimensions. Maybe try to unhide the readout mode in the driver options. I hide it because some software gets confused by it as for SBIG it sets the readout mode but also the resolution (which is a weird SBIG cameras do).

MY driver is ASCOM. There is no AO standard in ASCOM, so I can't provide access to it. Prism, SkyX, MaximDL and others can access the AO because they don't use ASCOM. They go straight to the underlying system driver, like my driver does. So unfortunately, until ASCOM publishes an AO interface for clients, I can't provide access to it. Which is annoying.

**Comment by stxlissues** [comment]
Thanks Cedric.  Seems like a problem beyond my ability to resolve, both on the setting the readout mode and in driving an AO unit.  
Nice work you've done though.
-Al

**Comment by cedric-r** [comment]
The readout mode is easy: in the same place you activated logging, there is a checkbox "hide readout". It's checked be default. Uncheck it and see if it makes any change to the way Prism or SkyX behave. It makes a difference for SGP.

For AO, I'm afraid there is no solution via ASCOM. The only possibility is to go straight to the underlying system driver, or create an interface the software recognises (e.g. SX Lodestar) and translate the commands to the SBIG AO. But without access to any AO system I can't do that.

**Comment by stxlissues** [comment]
Cedric,

Rookie mistake!!

Normally the images had come out full frame, but the new driver installation apparently defaulted to a different window size in Prism.  Once I set the display to Full frame (see pic), it all appeared to work correctly.  By the way, unchecking the readout box made no difference.

 

Too bad about the AO-X unit.  I’d really like to have that working.  It works but I cannot get it to calibrate the camera with the mount, so guiding with the AO unit doesn’t work for more than a couple of minutes before the mount has moved too far for the AO to correct.  My uneducated guess is that the imaging software ( Prism or SkyX) is not translating the SBIG relays for the mount, which I believe is expecting pulses.  But already I’m out of my depth.  The AO  unit does appear to calibrate when using MaximDL, and maybe that’s to be expected as the software and hardware were from the same company.  Since taking the AO unit out of my imaging train, I’m back to 0.5 - 2 second guiding with an external guide camera instead of the 0.05 – 0.25 second guiding with the AO unit.  I would offer to lend you my AO-X unit to develop a driver, but that would be up to you if you have the time, desire or SBIG camera/FW to accommodate the unit.  Let me know.

-Al

**Comment by cedric-r** [comment]
The problem is that there isn't a standard interface for AOs. Phd knows of one (SX), and Maxim DL of another (SBIG). So various programs can implement specific drivers for specific AOs, but it can't be generic. I don't know why ASCOM didn't define a standard interface for them. So even if I created a driver the SBIG AOs, the interface wouldn't be known by any software, so that would be useless. All I could do is create an emulator for SX for example, and the few things that know about could communicate with the SBIG AO. But that would be a bit dodgy and wouldn't help many people. It's very frustrating.
