### ISSUE TITLE
Error message when trying to connect to STF-402M

### ISSUE THREAD

**Issue by 4ks1** [cedric-r/ASCOM.HomeMade.SBIGCamera#9]
I am interested in this driver to use an older SBIG STF-402M as a guider camera. The camera works fine in MaxIm DL through the native SBIG Universal driver plugin. I tried to connect to the camera via the ASCOM driver plugin in MaxIm DL which fails with the attached error message. I have not yet tried connecting from other software or from scripts, but this error already hints at a non-conformity. The CanFastReadout property seems undefined, at least for this camera model. - https://ascom-standards.org/Help/Developer/html/P_ASCOM_DriverAccess_Camera_CanFastReadout.htm

Best,
4ks1

![Screenshot 2023-02-17 155627](https://user-images.githubusercontent.com/16147364/219885337-5a3ddbaa-bfd5-4b8d-900a-02b856ebd0ca.png)

**Comment by cedric-r** [comment]
Hi,

If you display the driver's options, you'll see a checkbox called "Hide readout". By default it's activated because SBIG cameras are very confusing regarding setting readout mode: it also sets resolution and some software doesn't expect that (it really doesn't make sense). If you uncheck that option, Maxim DL should be able to set the readout.
